---
title: '&#39;Исключение&#39; операнд должен быть производным от &#39;System.Exception&#39;'
ms.date: 07/20/2015
f1_keywords:
- vbc30665
- bc30665
helpviewer_keywords:
- BC30665
ms.assetid: 7c228087-39ea-4b30-a410-6ba711e67e5e
ms.openlocfilehash: 67f9d08338967e1cb5df201fde2bfc2b79639092
ms.sourcegitcommit: 3d5d33f384eeba41b2dff79d096f47ccc8d8f03d
ms.translationtype: MT
ms.contentlocale: ru-RU
ms.lasthandoff: 05/04/2018
ms.locfileid: "33609701"
---
# <a name="39throw39-operand-must-derive-from-39systemexception39"></a>&#39;Исключение&#39; операнд должен быть производным от &#39;System.Exception&#39;
Аргумент для `Throw` должен быть либо экземпляром `System.Exception` , либо экземпляром класса, производного от `System.Exception`.  
  
 **Идентификатор ошибки:** BC30665  
  
## <a name="to-correct-this-error"></a>Исправление ошибки  
  
-   Используйте аргумент, производный от `System.Exception`, как показано в приведенном ниже примере.  
  
    ```  
    Throw New System.Exception("This is an error.")  
    ```  
  
## <a name="see-also"></a>См. также  
 [Оператор Throw](../../visual-basic/language-reference/statements/throw-statement.md)  
 [Оператор Try...Catch...Finally](../../visual-basic/language-reference/statements/try-catch-finally-statement.md)  
 [Класс Exception в Visual Basic](http://msdn.microsoft.com/library/9aac396f-34ca-4afb-8e6c-e523cb690ba9)  
 [Исключения и обработка ошибок в Visual Basic](http://msdn.microsoft.com/library/3e351e73-cf23-40ab-8b60-05794160529e)
